### ISSUE TITLE
Feature Request: OC Editor - Movable Cuts

### ISSUE THREAD

**Issue by kai-wng-uos** [opencast/opencast-editor#1228] opened 2023-12-05 07:49 UTC
It would be very helpful to be able to move cuts made on the waveform, either via drag'n drop or typing in timestamps (this was possible in the old version of the editor, though it was a bit finnicky). Having both options would be ideal.

**Comment by Arnei** [comment] 2023-12-05 12:56
Possible duplicate of #1132

**Closed** 2024-02-16 12:53 UTC
